version: 1.0.{build}
image:
- Visual Studio 2019 Preview
- Visual Studio 2013
- Visual Studio 2019
- Visual Studio 2017
- Visual Studio 2015
clone_folder: c:\appveyor-get-file-list
init:
# - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
- ps: Set-Location $env:APPVEYOR_BUILD_FOLDER
- ps: . .\env.ps1
- ps: .\setup.ps1
- ps: .\nuget.ps1
- ps: .\psgallery.ps1
- ps: .\pester.ps1
- ps: .\_7Zip4Powershell.ps1
build_script:
- ps: . .\env.ps1
- ps: .\client.ps1
test_script:
- ps: . .\test.ps1
after_test:
- ps: $fname = 'all.xz'; Get-ChildItem $fname | % { Push-AppveyorArtifact $_.FullName -FileName $fname }
- ps: $fname = 'all.7z'; Get-ChildItem $fname | % { Push-AppveyorArtifact $_.FullName -FileName $fname }
on_failure:
- ps: $fname = 'all.xz'; Get-ChildItem $fname | % { Push-AppveyorArtifact $_.FullName -FileName $fname }
- ps: $fname = 'all.7z'; Get-ChildItem $fname | % { Push-AppveyorArtifact $_.FullName -FileName $fname }
